// Auto-generated by Supabase MCP `generate_typescript_types`.
// Regenerate after schema changes.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  __InternalSupabase: { PostgrestVersion: "14.5" };
  public: {
    Tables: {
      groups: {
        Row: {
          id: number;
          slug: string;
          name: string;
          created_by: string;
          created_at: string;
        };
        Insert: {
          id?: never;
          slug: string;
          name: string;
          created_by: string;
          created_at?: string;
        };
        Update: {
          id?: never;
          slug?: string;
          name?: string;
          created_by?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      group_members: {
        Row: {
          group_id: number;
          user_id: string;
          joined_at: string;
          role: "creator" | "member";
        };
        Insert: {
          group_id: number;
          user_id: string;
          joined_at?: string;
          role?: "creator" | "member";
        };
        Update: {
          group_id?: number;
          user_id?: string;
          joined_at?: string;
          role?: "creator" | "member";
        };
        Relationships: [];
      };
      plays: {
        Row: {
          id: number;
          user_id: string;
          played_at: string;
          played_date: string;
          outcome: "survive" | "death";
          reason: string;
          total_slices: number;
          streak_at_play: number;
          points_earned: number;
        };
        Insert: {
          id?: never;
          user_id: string;
          played_at?: string;
          played_date: string;
          outcome: "survive" | "death";
          reason: string;
          total_slices: number;
          streak_at_play: number;
          points_earned?: number;
        };
        Update: {
          id?: never;
          user_id?: string;
          played_at?: string;
          played_date?: string;
          outcome?: "survive" | "death";
          reason?: string;
          total_slices?: number;
          streak_at_play?: number;
          points_earned?: number;
        };
        Relationships: [];
      };
      game_sentences: {
        Row: {
          id: number;
          text: string;
          type: string; // "survive" | "death"
          time_slot: string | null; // "morning" | "noon" | "afternoon" | "night" | "general"
          status: string | null; // "pending" | "approved" | "rejected"
          created_at: string | null;
        };
        Insert: {
          id?: number;
          text: string;
          type: string;
          time_slot?: string | null;
          status?: string | null;
          created_at?: string | null;
        };
        Update: {
          id?: number;
          text?: string;
          type?: string;
          time_slot?: string | null;
          status?: string | null;
          created_at?: string | null;
        };
        Relationships: [];
      };
      user_suggestions: {
        Row: {
          created_at: string;
          id: number;
          is_approved: boolean | null;
          suggested_by: string | null;
          text: string;
          tier: number | null;
          type: string | null;
        };
        Insert: {
          created_at?: string;
          id?: never;
          is_approved?: boolean | null;
          suggested_by?: string | null;
          text: string;
          tier?: number | null;
          type?: string | null;
        };
        Update: {
          created_at?: string;
          id?: never;
          is_approved?: boolean | null;
          suggested_by?: string | null;
          text?: string;
          tier?: number | null;
          type?: string | null;
        };
        Relationships: [];
      };
      users: {
        Row: {
          current_streak: number | null;
          has_played_ever: boolean | null;
          highest_streak: number | null;
          id: string;
          last_outcome: string | null;
          last_played_at: string | null;
          last_played_date: string | null;
          last_reason: string | null;
          madness_tag: string | null;
          nickname: string | null;
          referrer_id: string | null;
          rescue_pending: boolean | null;
          seen_reasons: string[] | null;
          streak_before_last_death: number | null;
          total_score: number | null;
          username: string | null;
        };
        Insert: {
          current_streak?: number | null;
          has_played_ever?: boolean | null;
          highest_streak?: number | null;
          id: string;
          last_outcome?: string | null;
          last_played_at?: string | null;
          last_played_date?: string | null;
          last_reason?: string | null;
          madness_tag?: string | null;
          nickname?: string | null;
          referrer_id?: string | null;
          rescue_pending?: boolean | null;
          seen_reasons?: string[] | null;
          streak_before_last_death?: number | null;
          total_score?: number | null;
          username?: string | null;
        };
        Update: {
          current_streak?: number | null;
          has_played_ever?: boolean | null;
          highest_streak?: number | null;
          id?: string;
          last_outcome?: string | null;
          last_played_at?: string | null;
          last_played_date?: string | null;
          last_reason?: string | null;
          madness_tag?: string | null;
          nickname?: string | null;
          referrer_id?: string | null;
          rescue_pending?: boolean | null;
          seen_reasons?: string[] | null;
          streak_before_last_death?: number | null;
          total_score?: number | null;
          username?: string | null;
        };
        Relationships: [];
      };
    };
    Views: { [_ in never]: never };
    Functions: { [_ in never]: never };
    Enums: { [_ in never]: never };
    CompositeTypes: { [_ in never]: never };
  };
};

// Convenience non-null aliases for app code (DB columns are nullable but our
// app treats them as defaulted via Postgres defaults / trigger inserts).
export interface UserRow {
  id: string;
  username: string;
  nickname: string | null;
  total_score: number;
  current_streak: number;
  highest_streak: number;
  madness_tag: string;
  seen_reasons: string[];
  last_played_date: string | null;
  last_outcome: "survive" | "death" | null;
  last_reason: string | null;
  referrer_id: string | null;
  streak_before_last_death: number | null;
  rescue_pending: boolean;
  has_played_ever: boolean;
}

// Apply Postgres defaults so the app can treat the row as fully populated.
type RawUserRow = Database["public"]["Tables"]["users"]["Row"];
export function normalizeUserRow(r: RawUserRow): UserRow {
  return {
    id: r.id,
    username: r.username ?? "ישראלי",
    nickname: r.nickname,
    total_score: r.total_score ?? 0,
    current_streak: r.current_streak ?? 0,
    highest_streak: r.highest_streak ?? 0,
    madness_tag: r.madness_tag ?? "ישראלי ממוצע",
    seen_reasons: r.seen_reasons ?? [],
    last_played_date: r.last_played_date,
    last_outcome:
      r.last_outcome === "survive" || r.last_outcome === "death" ? r.last_outcome : null,
    last_reason: r.last_reason,
    referrer_id: r.referrer_id,
    streak_before_last_death: r.streak_before_last_death,
    rescue_pending: r.rescue_pending ?? false,
    has_played_ever: r.has_played_ever ?? false,
  };
}

export interface GroupRow {
  id: number;
  slug: string;
  name: string;
  created_by: string;
  created_at: string;
}

export interface GroupMemberRow {
  group_id: number;
  user_id: string;
  joined_at: string;
  role: "creator" | "member";
}

export interface PlayRow {
  id: number;
  user_id: string;
  played_at: string;
  played_date: string;
  outcome: "survive" | "death";
  reason: string;
  total_slices: number;
  streak_at_play: number;
  points_earned: number;
}

export interface UserSuggestionRow {
  id: number;
  text: string;
  type: "survive" | "death";
  tier: number | null;
  suggested_by: string | null;
  is_approved: boolean;
  created_at: string;
}
